<?php 
$this->headLink()->appendStylesheet("//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css");
$this->inlineScript()->appendFile("//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js");
$this->inlineScript()->appendFile("//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js");
?>
<?= $this->form?>
<h2>Liste des divers Travaux</h2>
<hr />
<a href="<?= $this->url(array(), 'otherWorkAdd')?>" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-plus"></span> Nouveau Travail</a>
<hr />

<?= count($this->messages) ? '<p>' . implode('<br />',$this->messages) . '</p>' : '' ?>

<table id="otherworks" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Nom</th>
            <th>Techno</th>
            <th>Description</th>
            <th>Lien</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?= $this->partialLoop('/otherwork/partials/item-list.phtml', $this->otherworks)?>
    </tbody>
</table>
    
<script>
<?php $this->inlineScript()->captureStart() ?>
$(document).ready(function() {
	$('#otherworks').dataTable();
} );
<?php $this->inlineScript()->captureEnd() ?>
</script>