<?= $this->doctype() . PHP_EOL ?>
<html>
    <head>
        <?php
            $this->headTitle('Mon Appli')->setSeparator(' - ');
            echo $this->headTitle() . PHP_EOL;
            
            $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
            echo $this->headMeta() . PHP_EOL;
            
            $this->headLink()->appendStylesheet("/assets/bootstrap/dist/css/bootstrap.min.css");
            $this->headLink()->appendStylesheet("/css/style.css");
            
            echo $this->headLink() . PHP_EOL;
            
            echo $this->headStyle() . PHP_EOL;
            
            echo $this->headScript() . PHP_EOL;
            
        ?>
    </head>
    <body>
    <div class="container">
	   <?php 
	       
            $config = new Zend_Config_Xml(APPLICATION_PATH . '/configs/navigation.xml', 'nav');	   
	        $container = new Zend_Navigation($config);
	        
	        /* @var $navigation Zend_View_Helper_Navigation */
	        $navigation = $this->navigation($container);
	        $navigation->setAcl(Zend_Registry::get('Zend_Acl'));
	        
	        $auth = Zend_Auth::getInstance();
	        if($auth->hasIdentity()){
	            $userAuth = $auth->getIdentity();
	        } else {
	            $userAuth = new Model_User();
	        }
	        $navigation->setRole($userAuth);
	        
	        /* @var $menu Zend_View_Helper_Navigation_Menu */
	        $menu = $navigation->menu();
	        $menu->setPartial('partials/exemple.phtml');
	        
	        echo $menu;
	        
	        /* @var $breadcrumbs Zend_View_Helper_Navigation_Breadcrumbs */
	        $breadcrumbs = $navigation->breadcrumbs();
	        $breadcrumbs->setMinDepth(1);
	        
	        echo $breadcrumbs;
	   ?>
	    <div class="header">
         <h3 class="text-muted">Project name</h3>
       </div>
      <?= $this->partial('partials/priorityMessages.phtml', array('priorityMessages'=> $this->priorityMessenger())); ?>
      <?= $this->layout()->content?>
      <footer class="footer">
        <p>© Company 2014</p>
      </footer>
	</div>
	 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<?php
$this->inlineScript()->prependFile('/js/menu.js');
$this->inlineScript()->prependFile('/js/jquery.easing.1.3.js');
$this->inlineScript()->prependFile('/assets/bootstrap/dist/js/bootstrap.min.js');
$this->inlineScript()->prependFile('/assets/jquery/dist/jquery.min.js');


?>
<?= $this->inlineScript() . PHP_EOL?>
<!-- <div class="row affix-row"> -->
<!--     <div class="col-sm-3 col-md-2 affix-sidebar"> -->
<!--         <div class="sidebar-nav"> -->
<!--   <div class="navbar navbar-default" role="navigation"> -->
<!--     <div class="navbar-header"> -->
<!--       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse"> -->
<!--       <span class="sr-only">Toggle navigation</span> -->
<!--       <span class="icon-bar"></span> -->
<!--       <span class="icon-bar"></span> -->
<!--       <span class="icon-bar"></span> -->
<!--       </button> -->
<!--       <span class="visible-xs navbar-brand">Sidebar menu</span> -->
<!--     </div> -->
<!--     <div class="navbar-collapse collapse sidebar-navbar-collapse"> -->
<!--       <ul class="nav navbar-nav" id="sidenav01"> -->
<!--         <li class="active"> -->
<!--           <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01" class="collapsed"> -->
<!--           <h4> -->
<!--           Portfolio -->
<!--           </h4> -->
<!--           </a> -->
          <div class="collapse" id="toggleDemo0" style="height: 0px;">
<!--             <ul class="nav nav-list"> -->
<!--               <li><a href="#">ProfileSubMenu1</a></li> -->
<!--               <li><a href="#">ProfileSubMenu2</a></li> -->
<!--               <li><a href="#">ProfileSubMenu3</a></li> -->
<!--             </ul> -->
<!--           </div> -->
<!--         </li> -->
<!--         <li> -->
<!--           <a href="#" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed"> -->
<!--           <span class="glyphicon glyphicon-cloud"></span> Accueil <span class="caret pull-right"></span> -->
<!--           </a> -->
<!--         </li> -->
<!--         <li class=""> -->
<!--           <a href="/" data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01" class="collapsed"> -->
<!--           <span class="glyphicon glyphicon-inbox"></span> Index <span class="caret pull-right"></span> -->
<!--           </a> -->
<!--         </li> -->
<!--       <li class=""><a href="<?//= $this->url(array(), 'webIndex')?>"><span class="glyphicon glyphicon-lock"></span> Utilisateurs</a></li>
        <li class=""><a href="<?//= $this->url(array(), 'progressIndex')?>"><span class="glyphicon glyphicon-book"></span> Etudes</a></li>
        <li class=""><a href="<?//= $this->url(array(), 'contactIndex')?>"><span class="glyphicon glyphicon-envelope"></span> Contactez moi</a></li>
<!--       </ul> -->
      </div><!--/.nav-collapse -->
<!--     </div> -->
<!--   </div> -->
<!--     </div> -->
        
<!--     <div class="col-sm-9 col-md-10 affix-content"> -->
<!--         <div class="container"> -->
<!--             <div class="page-header"> -->
                 <?//= $this->partial('partials/priorityMessages.phtml', array('priorityMessages'=> $this->priorityMessenger())); ?>
                  <?//= $this->layout()->content?>
<!--             </div> -->
<!--         </div> -->
<!--     </div> -->
<!--     </div>  -->
    <?php
//      $this->inlineScript()->prependFile('/assets/bootstrap/dist/js/bootstrap.min.js');
//      $this->inlineScript()->prependFile('/assets/jquery/dist/jquery.min.js');
//      echo $this->inlineScript() . PHP_EOL;
//      ?>
<!--     </body> -->
<!-- </html> -->